Description:  Udacity - Design for Availability, Resilience, and Reliability

Parameters:
  MainVPCID:
    Description: Main VPC ID
    Type: String

  DRVPCID:
    Description: Disaster Recovery VPC ID
    Type: String

  MainPrivateRouteTable:
    Description: Main Private Route Table
    Type: String

  DRPrivateRouteTable:
    Description: Disaster Recovery Private Route Table
    Type: String

  DRAcceptRegion:
    Description: Disaster Recovery Private Route Table
    Type: String

Resources:

  # PeeringRoute1:
  #   Type: 'AWS::EC2::Route'
  #   Properties:
  #     DestinationCidrBlock: 0.0.0.0/0
  #     RouteTableId: !Ref DRPrivateRouteTable
  #     VpcPeeringConnectionId: !Ref myVPCPeeringConnection

  PeeringRoute2:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 172.31.0.0/16
      RouteTableId: !Ref MainPrivateRouteTable
      VpcPeeringConnectionId: !Ref myVPCPeeringConnection

  myVPCPeeringConnection:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId: !Ref MainVPCID
      PeerVpcId: !Ref DRVPCID
      PeerRegion: !Ref DRAcceptRegion

Outputs:
  PeeringVPC:
    Description: Peering VPC ID
    Value: !Ref myVPCPeeringConnection
    Export:
      Name: !Join [ ':', [ !Ref 'AWS::StackName', 'PeeringVPC' ] ]
